package com.ngosha.contactcleaner

import android.Manifest
import android.app.Activity
import android.content.ContentUris
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.provider.ContactsContract
import android.provider.MediaStore
import android.view.View
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import java.security.MessageDigest
import kotlin.concurrent.thread

class MainActivity : AppCompatActivity() {
 data class MediaItem(val id:Long,val uri:Uri,val name:String,val size:Long,val type:String)
 data class ContactItem(val id:Long,val name:String,val number:String,val normalized:String)
 private lateinit var status:TextView; private lateinit var details:TextView; private lateinit var clean:Button
 private lateinit var total:TextView; private lateinit var dups:TextView; private lateinit var space:TextView; private lateinit var progress:ProgressBar; private lateinit var progressText:TextView
 private var mediaGroups:List<List<MediaItem>> = emptyList(); private var contactGroups:List<List<ContactItem>> = emptyList(); private var selectedDelete:List<MediaItem> = emptyList(); private var pendingDelete:List<Uri> = emptyList()
 private val PERM=91; private val DELETE_REQ=92
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.statusText);details=findViewById(R.id.detailsText);clean=findViewById(R.id.cleanButton);total=findViewById(R.id.totalText);dups=findViewById(R.id.duplicateText);space=findViewById(R.id.deletedText);progress=findViewById(R.id.progressBar);progressText=findViewById(R.id.progressText);findViewById<Button>(R.id.scanButton).setOnClickListener{requestMediaAndScan("all")};findViewById<Button>(R.id.photosButton).setOnClickListener{requestMediaAndScan("image")};findViewById<Button>(R.id.videosButton).setOnClickListener{requestMediaAndScan("video")};findViewById<Button>(R.id.audioButton).setOnClickListener{requestMediaAndScan("audio")};findViewById<Button>(R.id.contactsButton).setOnClickListener{requestContacts()};clean.setOnClickListener{confirmClean()}}
 private fun mediaPermissions():Array<String> = if(Build.VERSION.SDK_INT>=33) arrayOf(Manifest.permission.READ_MEDIA_IMAGES,Manifest.permission.READ_MEDIA_VIDEO,Manifest.permission.READ_MEDIA_AUDIO) else arrayOf(Manifest.permission.READ_EXTERNAL_STORAGE)
 private fun requestMediaAndScan(kind:String){val p=mediaPermissions();if(p.all{ContextCompat.checkSelfPermission(this,it)==PackageManager.PERMISSION_GRANTED})scanMedia(kind) else {getSharedPreferences("n",0).edit().putString("kind",kind).apply();ActivityCompat.requestPermissions(this,p,PERM)}}
 private fun requestContacts(){val p=arrayOf(Manifest.permission.READ_CONTACTS);if(p.all{ContextCompat.checkSelfPermission(this,it)==PackageManager.PERMISSION_GRANTED})scanContacts() else ActivityCompat.requestPermissions(this,p,PERM+1)}
 override fun onRequestPermissionsResult(r:Int,p:Array<out String>,g:IntArray){super.onRequestPermissionsResult(r,p,g);if(r==PERM&&g.any{it==PackageManager.PERMISSION_GRANTED})scanMedia(getSharedPreferences("n",0).getString("kind","all")?:"all") else if(r==PERM+1&&g.isNotEmpty()&&g[0]==PackageManager.PERMISSION_GRANTED)scanContacts() else status.text="Ruhusa inahitajika ili kufanya scan."}
 private fun begin(label:String){clean.isEnabled=false;selectedDelete=emptyList();progress.visibility=View.VISIBLE;progress.isIndeterminate=true;progressText.text=label;status.text=label;details.text="Inachambua kwa smart engine..."}
 private fun scanMedia(kind:String){begin("Inafanya Smart Fast Scan...");thread{val items=loadMedia(kind);runOnUiThread{total.text="${items.size}\nScanned";progress.isIndeterminate=false;progress.max=100;progress.progress=20;progressText.text="20% • Metadata scan imekamilika"};val candidates=items.groupBy{it.size}.values.filter{it.size>1}.flatten();val groups=mutableListOf<List<MediaItem>>();var done=0;val count=candidates.size.coerceAtLeast(1);candidates.groupBy{it.size}.values.forEach{bucket->groups.addAll(bucket.groupBy{hash(it.uri)}.values.filter{it.size>1});done+=bucket.size;val pct=20+(done*75/count);runOnUiThread{progress.progress=pct.coerceAtMost(95);progressText.text="$pct% • Inathibitisha ${done}/${candidates.size}"}};mediaGroups=groups.map{chooseKeepFirst(it)};contactGroups=emptyList();selectedDelete=mediaGroups.flatMap{it.drop(1)};val extra=selectedDelete.size;val bytes=selectedDelete.sumOf{it.size};val preview=mediaGroups.take(50).mapIndexed{index,g->buildString{append("KUNDI ${index+1} • ${g.first().type.uppercase()}\n");append("✓ KEEP  ${g.first().name}  •  ${format(g.first().size)}\n");g.drop(1).forEach{append("☑ DELETE  ${it.name}  •  ${format(it.size)}\n")}}}.joinToString("\n");runOnUiThread{progress.progress=100;progressText.text="100% • Scan imekamilika";status.text=if(extra==0)"✓ Hakuna exact duplicates." else "✓ $extra duplicates zimechaguliwa. Copy 1 ya KEEP imehifadhiwa katika kila kundi.";dups.text="$extra\nSelected";space.text="${format(bytes)}\nRecoverable";details.text=if(preview.isBlank())"Simu yako iko safi kwa category hii." else preview;clean.text="FUTA DUPLICATES $extra";clean.isEnabled=extra>0;progress.postDelayed({progress.visibility=View.GONE},600)}}}
 private fun chooseKeepFirst(group:List<MediaItem>):List<MediaItem>{return group.sortedWith(compareBy<MediaItem>{it.name.length}.thenBy{it.id})}
 private fun loadMedia(kind:String):List<MediaItem>{val out=mutableListOf<MediaItem>();fun q(uri:Uri,type:String){val pr=arrayOf(MediaStore.MediaColumns._ID,MediaStore.MediaColumns.DISPLAY_NAME,MediaStore.MediaColumns.SIZE);contentResolver.query(uri,pr,"${MediaStore.MediaColumns.SIZE}>0",null,null)?.use{c->while(c.moveToNext()){val id=c.getLong(0);out+=MediaItem(id,ContentUris.withAppendedId(uri,id),c.getString(1)?:"file",c.getLong(2),type)}}};when(kind){"image"->q(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,"image");"video"->q(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,"video");"audio"->q(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,"audio");else->{q(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,"image");q(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,"video");q(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,"audio")}};return out}
 private fun hash(uri:Uri):String{return try{val md=MessageDigest.getInstance("SHA-256");contentResolver.openInputStream(uri)?.use{ins->val buf=ByteArray(128*1024);while(true){val n=ins.read(buf);if(n<=0)break;md.update(buf,0,n)}};md.digest().joinToString(""){"%02x".format(it)}}catch(_:Exception){"ERR-${uri}"}}
 private fun norm(s:String):String{var n=s.filter{it.isDigit()};if(n.startsWith("00255"))n=n.drop(2);return when{n.startsWith("255")&&n.length==12->n;n.startsWith("0")&&n.length==10->"255"+n.drop(1);n.length==9&&(n[0]=='6'||n[0]=='7')->"255$n";else->n}}
 private fun scanContacts(){begin("Inakagua Contacts...");thread{val a=mutableListOf<ContactItem>();val pr=arrayOf(ContactsContract.CommonDataKinds.Phone.CONTACT_ID,ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,ContactsContract.CommonDataKinds.Phone.NUMBER);contentResolver.query(ContactsContract.CommonDataKinds.Phone.CONTENT_URI,pr,null,null,null)?.use{c->while(c.moveToNext()){val num=c.getString(2)?:continue;a+=ContactItem(c.getLong(0),c.getString(1)?:"Bila jina",num,norm(num))}};contactGroups=a.groupBy{it.normalized}.values.map{it.distinctBy{x->x.id}}.filter{it.size>1};mediaGroups=emptyList();selectedDelete=emptyList();val extra=contactGroups.sumOf{it.size-1};runOnUiThread{progress.visibility=View.GONE;total.text="${a.distinctBy{it.id}.size}\nContacts";dups.text="$extra\nDuplicates";space.text="Smart\nMerge";status.text="Tumepata duplicate contacts $extra.";details.text=contactGroups.take(60).joinToString("\n\n"){"✓ KEEP ${it.first().name} • ${it.first().normalized}\n${it.size-1} duplicates za ku-merge"};clean.isEnabled=false;progressText.text="Contacts Smart Merge"}}}
 private fun confirmClean(){if(selectedDelete.isEmpty())return;val bytes=selectedDelete.sumOf{it.size};AlertDialog.Builder(this).setTitle("Futa duplicates zilizochaguliwa?").setMessage("Safety Lock imewashwa. Copy moja ya KEEP haitafutwa katika kila kundi.\n\nDELETE: ${selectedDelete.size} files\nKEEP: ${mediaGroups.size} unique originals\nSpace: ${format(bytes)}\n\nAndroid inaweza kuomba uthibitisho mmoja wa deletion.").setNegativeButton("GHAIRI",null).setPositiveButton("FUTA DUPLICATES"){_,_->deleteMedia(selectedDelete)}.show()}
 private fun deleteMedia(items:List<MediaItem>){pendingDelete=items.map{it.uri};if(Build.VERSION.SDK_INT>=30){try{val pi=MediaStore.createDeleteRequest(contentResolver,pendingDelete);startIntentSenderForResult(pi.intentSender,DELETE_REQ,null,0,0,0)}catch(e:Exception){status.text="Deletion haijaanza: ${e.message}"}}else{var n=0;items.forEach{try{n+=contentResolver.delete(it.uri,null,null)}catch(_:Exception){}};finishDelete(n)}}
 override fun onActivityResult(r:Int,c:Int,d:android.content.Intent?){super.onActivityResult(r,c,d);if(r==DELETE_REQ){if(c==Activity.RESULT_OK)finishDelete(pendingDelete.size) else status.text="Deletion imeghairiwa. Files zako hazijabadilishwa."}}
 private fun finishDelete(n:Int){status.text="✓ Imekamilika. $n duplicates zimeondolewa na originals zimebaki.";dups.text="0\nSelected";space.text="Done\nCleaned";details.text="Safety Lock: copy moja unique imeachwa katika kila duplicate group. Fanya Smart Scan tena kuthibitisha.";clean.text="FUTA DUPLICATES";clean.isEnabled=false;selectedDelete=emptyList();mediaGroups=emptyList()}
 private fun format(b:Long):String{val mb=b/1048576.0;return if(mb>=1024)"%.2f GB".format(mb/1024) else "%.1f MB".format(mb)}
}
